language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm 

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=0
# disable the default submodule logic
git:
  submodules: false
 
before_script:
    - composer self-update
    - composer install
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
before_deploy:
    - composer self-update
    - composer install
    - npm install
    - grunt
deploy:
  provider: releases
  file: build/wpbp.zip
  skip_cleanup: true
  api-key:
    secure: secure_key
  on:
    tags: true
