web:
    build: nginx/.
    ports:
        - '80:80'
    links:
        - php
    volumes:
        - '~/Kitematic/.tmp/wpbp:/wp'
    env_file: config.env
php:
    build: php/.
    ports:
        - '9000:9000'
    links:
        - db
    volumes:
        - '~/Kitematic/.tmp/wpbp:/wp'
    env_file: config.env
db:
    build: mysql/.
    env_file: config.env
